logging:
  level:
    web: TRACE
    org:
      springframework:
        web:
          socket: TRACE
        messaging: TRACE

spring:

  application:
    name: zuum

  datasource:
    #driver-class-name: org.h2.Driver 
    #url: jdbc:h2:mem:testdb 
    url: jdbc:postgresql://localhost:5432/postgres 
    username: postgresUser
    password: password
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true

api:
  security:    
    token:
      secret: ${JWT_SECRET:zuum-secret}